# SPDX-FileCopyrightText: 2024 Christina SÃ¸rensen
#
# SPDX-License-Identifier: EUPL-1.2

[bans]
multiple-versions = 'allow'

[licenses]
private = { ignore = true }
allow = ["MIT", "Apache-2.0", "EUPL-1.2", "Unicode-DFS-2016"]
